import NavBar from "../components/NavBar";

const Extraclass = ({max}) => {
  console.log(max)
  return(
    <div className="bg-[#181818] relative font-Kanit">
      <div className="sticky top-0 z-50">
        <NavBar page={2} max={max}/>
      </div>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Interdum velit laoreet id donec ultrices tincidunt arcu non sodales. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Ut placerat orci nulla pellentesque dignissim enim. Aliquam sem fringilla ut morbi tincidunt augue. Egestas sed tempus urna et. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Sagittis eu volutpat odio facilisis mauris sit. Eu facilisis sed odio morbi quis commodo odio aenean sed. Eget est lorem ipsum dolor sit. Velit scelerisque in dictum non. Orci eu lobortis elementum nibh tellus molestie. Turpis in eu mi bibendum neque egestas. Consequat ac felis donec et.

Purus viverra accumsan in nisl nisi scelerisque. Proin sed libero enim sed faucibus. Faucibus et molestie ac feugiat. Orci a scelerisque purus semper. Laoreet non curabitur gravida arcu ac tortor dignissim. Magnis dis parturient montes nascetur ridiculus mus. Scelerisque fermentum dui faucibus in ornare quam viverra orci sagittis. Sapien pellentesque habitant morbi tristique senectus. Fringilla urna porttitor rhoncus dolor purus non enim praesent. Pretium fusce id velit ut tortor. Pellentesque nec nam aliquam sem et tortor consequat id porta.

Et tortor consequat id porta. Vel risus commodo viverra maecenas. Convallis posuere morbi leo urna. Neque gravida in fermentum et sollicitudin ac orci. At erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Mollis nunc sed id semper risus in hendrerit gravida. Facilisis leo vel fringilla est ullamcorper eget. Id donec ultrices tincidunt arcu. Ultricies mi eget mauris pharetra et ultrices neque. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Mattis vulputate enim nulla aliquet porttitor lacus. Neque viverra justo nec ultrices dui sapien eget mi. Ullamcorper malesuada proin libero nunc consequat interdum. Eget dolor morbi non arcu risus quis varius quam. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Tristique senectus et netus et malesuada fames ac turpis egestas. Eget nullam non nisi est sit amet facilisis. Fermentum et sollicitudin ac orci phasellus egestas. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu.

Velit scelerisque in dictum non. In metus vulputate eu scelerisque felis imperdiet proin. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Sit amet tellus cras adipiscing enim eu turpis egestas. Pellentesque dignissim enim sit amet venenatis urna. Sagittis orci a scelerisque purus semper eget duis at tellus. Cras adipiscing enim eu turpis egestas pretium. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. In ante metus dictum at tempor commodo ullamcorper a. Massa placerat duis ultricies lacus sed turpis tincidunt id aliquet. Odio facilisis mauris sit amet massa vitae tortor condimentum. Fames ac turpis egestas sed tempus urna et. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh. Vulputate mi sit amet mauris commodo quis.

In ornare quam viverra orci sagittis eu volutpat. Cursus in hac habitasse platea dictumst quisque sagittis purus. Sit amet consectetur adipiscing elit pellentesque. Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Neque laoreet suspendisse interdum consectetur libero id. Amet cursus sit amet dictum. Dui nunc mattis enim ut tellus. Eget nunc scelerisque viverra mauris in aliquam sem fringilla ut. Vel risus commodo viverra maecenas accumsan. Ullamcorper sit amet risus nullam eget felis eget.

Justo laoreet sit amet cursus. Id velit ut tortor pretium viverra suspendisse potenti. Penatibus et magnis dis parturient montes nascetur. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Volutpat sed cras ornare arcu. Tortor consequat id porta nibh venenatis cras sed felis eget. Malesuada bibendum arcu vitae elementum. Nisl vel pretium lectus quam. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Purus semper eget duis at tellus. Quis imperdiet massa tincidunt nunc pulvinar sapien. Sed id semper risus in. Leo a diam sollicitudin tempor id eu. Tempus quam pellentesque nec nam aliquam sem et tortor. At urna condimentum mattis pellentesque id nibh tortor. Dolor magna eget est lorem ipsum dolor sit amet. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Mattis aliquam faucibus purus in massa. At imperdiet dui accumsan sit amet nulla facilisi. Id aliquet lectus proin nibh.

Non tellus orci ac auctor augue mauris. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget egestas. Bibendum at varius vel pharetra. Risus sed vulputate odio ut enim blandit volutpat maecenas. Sed ullamcorper morbi tincidunt ornare massa. Elit at imperdiet dui accumsan sit amet. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Augue interdum velit euismod in pellentesque massa placerat duis ultricies. Tortor id aliquet lectus proin nibh nisl condimentum. Cras semper auctor neque vitae tempus quam pellentesque nec nam. In pellentesque massa placerat duis ultricies lacus sed. Justo nec ultrices dui sapien eget mi. Sit amet cursus sit amet dictum sit amet justo donec. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere lorem. Montes nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Et odio pellentesque diam volutpat commodo sed egestas egestas.

Blandit turpis cursus in hac. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Tellus in metus vulputate eu scelerisque felis imperdiet proin fermentum. Amet nulla facilisi morbi tempus iaculis urna id volutpat lacus. Lorem dolor sed viverra ipsum nunc. Congue quisque egestas diam in arcu cursus euismod quis viverra. Vulputate ut pharetra sit amet aliquam. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Aliquam sem et tortor consequat id porta. Mauris in aliquam sem fringilla ut morbi. Turpis massa sed elementum tempus egestas sed. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Semper eget duis at tellus at urna condimentum mattis. Adipiscing elit duis tristique sollicitudin nibh sit amet. Egestas purus viverra accumsan in nisl. Dignissim sodales ut eu sem integer vitae justo eget. At tempor commodo ullamcorper a lacus vestibulum sed arcu non.

Egestas pretium aenean pharetra magna. Amet consectetur adipiscing elit ut aliquam purus sit. Libero justo laoreet sit amet cursus sit. Posuere morbi leo urna molestie at elementum eu. Ornare lectus sit amet est placerat. At quis risus sed vulputate. Id diam maecenas ultricies mi eget mauris pharetra et. Sagittis eu volutpat odio facilisis mauris sit amet. Nisi quis eleifend quam adipiscing vitae proin sagittis nisl. Non diam phasellus vestibulum lorem sed risus ultricies. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium.

Sodales ut eu sem integer vitae justo. Eget sit amet tellus cras. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Vitae justo eget magna fermentum iaculis eu non diam phasellus. Sit amet nisl purus in mollis nunc sed id semper. Potenti nullam ac tortor vitae purus. Dapibus ultrices in iaculis nunc. In arcu cursus euismod quis viverra. Sit amet dictum sit amet justo donec enim diam. Sapien pellentesque habitant morbi tristique senectus et netus et. Gravida rutrum quisque non tellus orci ac. Proin libero nunc consequat interdum varius sit. Feugiat sed lectus vestibulum mattis ullamcorper velit. Sed felis eget velit aliquet sagittis. Diam in arcu cursus euismod quis viverra. Vitae suscipit tellus mauris a diam. Sit amet venenatis urna cursus eget nunc scelerisque viverra. Metus aliquam eleifend mi in nulla posuere.

Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Ut lectus arcu bibendum at varius vel pharetra vel turpis. Porta nibh venenatis cras sed felis. Rhoncus dolor purus non enim praesent elementum facilisis leo. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis nisl. Nullam vehicula ipsum a arcu. Praesent semper feugiat nibh sed. Enim facilisis gravida neque convallis a cras semper auctor neque. Interdum varius sit amet mattis vulputate enim. Quis enim lobortis scelerisque fermentum dui faucibus in. Nunc consequat interdum varius sit amet mattis vulputate.

Id ornare arcu odio ut. Interdum varius sit amet mattis vulputate enim nulla aliquet. Integer eget aliquet nibh praesent tristique magna sit amet. Sem nulla pharetra diam sit amet nisl suscipit adipiscing. Et malesuada fames ac turpis egestas sed. Arcu vitae elementum curabitur vitae nunc sed velit. Et malesuada fames ac turpis egestas sed tempus urna et. Purus sit amet volutpat consequat. Quam id leo in vitae turpis massa sed elementum. Sed euismod nisi porta lorem mollis aliquam ut porttitor leo. Tortor at auctor urna nunc id. Sapien nec sagittis aliquam malesuada. Et tortor at risus viverra adipiscing at in tellus. Morbi tempus iaculis urna id volutpat. Commodo nulla facilisi nullam vehicula ipsum a arcu. Pellentesque adipiscing commodo elit at imperdiet. Eget est lorem ipsum dolor sit amet. Quisque id diam vel quam elementum pulvinar.

Facilisis sed odio morbi quis commodo odio aenean sed adipiscing. Cras adipiscing enim eu turpis egestas. Et tortor at risus viverra adipiscing at in. Vel quam elementum pulvinar etiam non quam lacus. Eros donec ac odio tempor orci dapibus ultrices in iaculis. Enim sed faucibus turpis in. Montes nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Placerat vestibulum lectus mauris ultrices eros in. Sed augue lacus viverra vitae.

Nunc sed augue lacus viverra vitae. Pellentesque habitant morbi tristique senectus et netus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Tempus imperdiet nulla malesuada pellentesque elit eget gravida. Nisl rhoncus mattis rhoncus urna neque viverra justo nec. Morbi tristique senectus et netus et malesuada fames ac. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Fames ac turpis egestas sed tempus urna et pharetra. Auctor urna nunc id cursus metus. Dictum at tempor commodo ullamcorper a lacus vestibulum sed arcu. Feugiat sed lectus vestibulum mattis ullamcorper velit. Arcu bibendum at varius vel pharetra vel turpis. Fermentum iaculis eu non diam. Nam aliquam sem et tortor consequat. Egestas maecenas pharetra convallis posuere morbi leo urna molestie. At ultrices mi tempus imperdiet nulla malesuada.

Vel risus commodo viverra maecenas. Tellus at urna condimentum mattis pellentesque id nibh. Eget velit aliquet sagittis id. At volutpat diam ut venenatis tellus in metus. Risus feugiat in ante metus. Auctor neque vitae tempus quam pellentesque. Nullam vehicula ipsum a arcu. Ullamcorper a lacus vestibulum sed arcu. Id faucibus nisl tincidunt eget nullam. Ac odio tempor orci dapibus ultrices in iaculis nunc sed. Tristique risus nec feugiat in fermentum posuere urna nec tincidunt. Sagittis nisl rhoncus mattis rhoncus. Habitant morbi tristique senectus et netus et. Vitae elementum curabitur vitae nunc sed velit dignissim sodales ut. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Eget nulla facilisi etiam dignissim. Mattis ullamcorper velit sed ullamcorper. Aliquam ultrices sagittis orci a scelerisque purus semper eget duis.</p>
    </div>
  )
}

export default Extraclass;